name: automate-react-s3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn build

      - name: Serve application locally
        run: |
          npm install -g serve
         serve -s build -l 0.0.0.0:5000 


